base_url = "https://psibi.in"
title = "Sibi"
description = "Sibi's blog"
compile_sass = false
generate_feeds = false
build_search_index = false
taxonomies = []
output_dir = "docs"
minify_html = false

[markdown]
render_emoji = false
external_links_target_blank = false
smart_punctuation = false

[markdown.highlighting]
theme = "github-light"

[extra]
author = "Sibi"
